version: '3.8'

services:
  # 백엔드 (Spring Boot)
  api:
    image: ghcr.io/sisc-it/sisc-web-back:${TAG:-latest} # TAG 변수가 없으면 latest 사용
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul                   # 시간대 설정 : 컨테이너 내부 환경변수
      - JAVA_OPTS=-Xmx2560M -Xms1G -XX:+UseG1GC -XX:MaxGCPauseMillis=200     # 자바 힙 메모리를 1GB ~ 2.5GB로 확장 (8GB 서버 기준)
    volumes:
      - /etc/localtime:/etc/localtime:ro  # 시간대 설정 : 호스트의 시간 설정 파일 공유
      - /etc/timezone:/etc/timezone:ro
      - /mnt/storage/logs:/app/logs
      - /mnt/storage/uploads:/app/uploadss
    networks:
      - sisc-net
    # 1GB 램 서버 생존을 위한 메모리 제한 (Docker 레벨)
    deploy:
      resources:
        limits:
          memory: 3500M                 # JVM 힙 외 여유 공간 포함 3.5GB 할당
        reservations:
          memory: 1G                 # 최소 1GB 보장
  redis:
    image: redis:alpine  # 가벼운 alpine 버전 사용
    container_name: redis
    restart: always
    command: redis-server --maxmemory 180mb --maxmemory-policy allkeys-lru
    networks:
      - sisc-net
    deploy:
      resources:
        limits:
          memory: 250M

  # 프론트엔드 (React + Nginx)
  web:
    image: ghcr.io/sisc-it/sisc-web-front:${TAG:-latest}
    container_name: web
    restart: always
    #ports: # NGINX로 인해 주석 처리
      # - "80:80"     # HTTP
      # - "443:443" # HTTPS (인증서 설정 필요 시 주석 해제)
    networks:
      - sisc-net
    deploy:
      resources:
        limits:
          memory: 512M

  # 3. AI
  ai:
    image: ghcr.io/sisc-it/sisc-web-ai:${TAG:-latest}
    container_name: ai
    restart: always
    ports:
      - "5000:5000"
    networks:
      - sisc-net
    deploy:
      resources:
        limits:
          memory: 2G                 # AI 모델 로드 시 필요한 메모리 확보
        reservations:
          memory: 512M
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      # 외부망(공유기)에서 들어오는 80, 443 요청을 NPM이 모두 받음
      - '80:80'
      - '443:443'
      - '81:81' # NPM 관리자 페이지 (접속: http://서버IP:81)
    volumes:
      - ./data/npm:/data               # NPM 설정 데이터 유지
      - ./data/letsencrypt:/etc/letsencrypt # SSL 인증서 데이터 유지
    networks:
      - sisc-net
    deploy:
      resources:
        limits:
          memory: 512M
networks:
  sisc-net:
    driver: bridge