spring:
  profiles:
    active: prod

  jpa:
    generate-ddl: true
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false       # 가로로 너무 길어지는 게 싫다면 이것도 false
        use_sql_comments: false # 부가 설명 제거

  servlet:    # 파일 설정
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  boot:
    admin:
      context-path: /admin/dev
      notify:
        mail:
          enabled: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info,metrics,logfile,httpexchanges,threaddump"
  endpoint:
    health:
      show-details: when_authorized
  health:
    mail:
      enabled: false

# Docker 로그 제한 
services:
  api:
    image: sisc-web-back:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100m"    # 파일 하나당 10MB로 제한
        max-file: "3"      # 최대 3개까지만 보관 (총 300MB 고정)

logging:
  file:
    name: /app/logs/application.log

springdoc:
  swagger-ui:
    tags-sorter: alpha  # 컨트롤러(Tag)를 알파벳/숫자 순으로 정렬